name = "btcmirror-submitter"

main = "src/index.ts"
compatibility_date = "2022-11-01"
node_compat = true

# Secrets: 
# - ETH_SUBMITTER_PRIVATE_KEY
# - GETBLOCK_API_KEY
# Run `echo <val> | wrangler secret put <key>`

[env.mainnet.vars]
BTCMIRROR_CONTRACT_ADDR="0x5fbdb2315678afecb367f032d93f642f64180aa3"
ETH_RPC_URL="http://127.0.0.1:8545"
BITCOIN_NETWORK="mainnet"
ETH_SUBMITTER_PRIVATE_KEY = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
GETBLOCK_API_KEY = "dcc70b70da044d63a4e4b7ef80d62bcd"

[env.testnet.vars]
BTCMIRROR_CONTRACT_ADDR="0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0"
ETH_RPC_URL="http://127.0.0.1:8545"
BITCOIN_NETWORK="testnet"
ETH_SUBMITTER_PRIVATE_KEY = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
GETBLOCK_API_KEY = "dcc70b70da044d63a4e4b7ef80d62bcd"

[triggers]
crons = [ "* * * * *" ]
